image: repo.us2.io/play-build

stages:
  - build
  - test
  - deploy

variables:
  _JAVA_OPTIONS: -Duser.home=${CI_PROJECT_DIR}/.java -Dsbt.boot.credentials=${CI_PROJECT_DIR}/.java/.ivy2/.credentials
  DOCKER_REGISTRY: registry.us2.io

package:
  stage: test
  tags:
    - aws
  script:
    - sbt clean compile test universal:packageZipTarball
    - mv target/universal/*.tgz docker/package.tar.gz
  artifacts:
    expire_in: 1 day
    paths:
      - docker/package.tar.gz

deploy:
  stage: deploy
  image: docker:1.10
  tags:
    - aws
  services:
    - docker:1.10-dind
  dependencies:
      - package
  tags:
    - dnd
  only:
    - master
  script:
    - docker build --build-arg APP_VER=${CI_BUILD_ID} -t ${DOCKER_REGISTRY}/${CONTAINER}:latest docker
    - docker tag ${DOCKER_REGISTRY}/${CONTAINER}:latest ${DOCKER_REGISTRY}/${CONTAINER}:build${CI_BUILD_ID}
    - docker push ${DOCKER_REGISTRY}/${CONTAINER}:build${CI_BUILD_ID}
    - docker push ${DOCKER_REGISTRY}/${CONTAINER}:latest
    - echo docker pull ${DOCKER_REGISTRY}/${CONTAINER}:build${CI_BUILD_ID}
