---
  swagger: "2.0"
  info:
    title: "USS Service Seed"
    description: "Describe me here"
    version: "1.0.0"
  host: stg.us2.io
  schemes:
    - "https"
  consumes:
    - application/json
  produces:
    - application/json
  definitions:
    ExampleModel:
      type: object
      properties:
        name:
          type: string
        age:
          type: number
